language: node_js
os: osx

node_js:
  - '10'

git:
  depth: 3

branches:
  only:
  - master

install:
  - yarn install

script:
  - yarn clean
  - yarn dev
  - yarn build

after_script:
  - yarn clean

cache:
  directaries:
    - node_modules
    - ~/.npm

jobs:
  include:
    - stage: test
      script: yarn format
    - stage: deploy
      script: yarn deploy

deploy:
  provider: digital-ocean
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: /
  on
    repo: gandres/backend-cici