name: BackendCici

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script:
            - mkdir backend 
            - cd backend 
            - git clone git@github.com:GandresCoello18/backend-cici.git
            - echo 'Deployment successful to digital ocean' 
            - cd backend-cici
            - yarn install
            - yarn build
            - pm2 start build/app.js
          artifacts:
            paths:
              - build
              - node_modules
          only:
            refs:
              - master
            changes:
              - /**/*